apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":"2025-01-01T00:05:11Z","generation":4,"name":"flask-ml-app-deployment","namespace":"default","resourceVersion":"124725","uid":"3881be02-09fb-4629-91e4-5c61f2ac5443"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"flask-ml-app"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"flask-ml-app"}},"spec":{"containers":[{"image":"praveenk205/flask-ml-app:v2","imagePullPolicy":"IfNotPresent","name":"flask-ml-app","ports":[{"containerPort":5000,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"regcred"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-01-01T00:11:36Z","lastUpdateTime":"2025-01-01T00:11:36Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-01-01T12:33:07Z","lastUpdateTime":"2025-01-01T12:33:07Z","message":"ReplicaSet \"flask-ml-app-deployment-b8444748c\" has timed out progressing.","reason":"ProgressDeadlineExceeded","status":"False","type":"Progressing"}],"observedGeneration":4,"readyReplicas":1,"replicas":2,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-01-01T00:05:11Z"
  generation: 5
  name: flask-ml-app-deployment
  namespace: default
  resourceVersion: "125414"
  uid: 3881be02-09fb-4629-91e4-5c61f2ac5443
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-ml-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-ml-app
    spec:
      containers:
      - image: praveenk205/flask-ml-app:v2
        imagePullPolicy: IfNotPresent
        name: flask-ml-app
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-01T00:11:36Z"
    lastUpdateTime: "2025-01-01T00:11:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-01T12:33:07Z"
    lastUpdateTime: "2025-01-01T12:33:07Z"
    message: ReplicaSet "flask-ml-app-deployment-b8444748c" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
